export const REQUEST_ALBUMS = 'ALBUMS/REQUEST_ALBUMS'
export const LOAD_ALBUMS = 'ALBUMS/LOAD_ALBUMS'
export const SET_ALBUMS = 'ALBUMS/SET_ALBUMS'
export const REMOVE_ALBUM = 'ALBUMS/REMOVE_ALBUM'
export const DELETE_ALBUM = 'ALBUMS/DELETE_ALBUM'


// export const FETCH_POSTS = 'POST/FETCH_POSTS'
// export const REQUEST_POSTS = 'POST/REQUEST_POSTS'
// export const SHOW_LOADER = 'APP/SHOW_LOADER'
// export const HIDE_LOADER = 'APP/HIDE_LOADER'
// export const SHOW_ALERT = 'APP/SHOW_ALERT'
// export const HIDE_ALERT = 'APP/HIDE_ALERT'